spring.application.name=HealthcareSystem

# Database config (you can keep MySQL off for now)
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db
spring.datasource.username=root
spring.datasource.password=2025

# JPA Settings (safe defaults)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JSP Path
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8080
